server:
  port: 8099
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/wlkg
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
wlkg:
  jwt:
    pubKeyPath: D:/tmp/rsa.pub # 公钥地址
    cookieName: WLKG_TOKEN


